<?php

namespace AppBundle\Repository;

/**
 * ArmadilloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmadilloRepository extends \Doctrine\ORM\EntityRepository
{
}
