<?php

namespace AppBundle\Repository;

/**
 * SquidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquidRepository extends \Doctrine\ORM\EntityRepository
{
}
